refactor(genbash): easier to add common path

diff --git a/genbash b/genbash
--- a/genbash
+++ b/genbash
@@ -23,19 +23,28 @@ export EX_USAGE=64 # Command line usage error
 ################################################################################
 # Dependency
 function check_dependency {
-	local common_path
-	if [ -f "${DIRNAME}/common.sh" ]; then
-		# shellcheck source=./common.sh
-		source "${DIRNAME}/common.sh"
-		common_path="${DIRNAME}/common.sh"
-	elif [ -f "$HOME/.local/share/bash-libs/common.sh" ]; then
-		# shellcheck disable=SC1090
-		source "$HOME/.local/share/bash-libs/common.sh"
-		common_path="$HOME/.local/share/bash-libs/common.sh"
-	else
-		echo "Could not find common.sh"
-		echo "Should be in ./ or in ~/.local"
-		exit "$EX_NOTFOUND"
+	local common_path=""
+	local search_common_path=(
+		"${DIRNAME}/common.sh"
+		"$HOME/.local/lib/bash-libs/common.sh"
+	)
+
+	for p in "${search_common_path[@]}"; do
+		if [ -f "$p" ]; then
+			# shellcheck source=./common.sh
+			source "$p"
+			common_path="$p"
+			break
+		fi
+	done
+
+	if [ "$common_path" = "" ]; then
+		echo "Could not find common.sh:"
+		for p in "${search_common_path[@]}"; do
+			echo "  $p"
+		done
+		echo "You could find it on: https://github.com/pbrideau/bash-libs"
+		exit 1
 	fi
 
 	local compare
